export const brand = {
  name: "Kisa African Coffee",
  shortName: "Kisa Coffee",
  foundationName: "Kisa Foundation Uganda",
  director: "Michael Kibuuka",
  tagline: "Premium Ugandan coffee for export buyers, connecting Central and Western Uganda to global markets while supporting the mission of Kisa Foundation Uganda.",
  email: "kibuuka@kisafoundationu.org",
  phone: "+256773640741",
  whatsapp: "+256773640741",
  country: "Uganda",
  location: "Uganda",
  regions: ["Central Uganda", "Western Uganda"],
  targetMarket: "Switzerland",
  visualStyle: "African Contemporary",
  quoteCta: "Request a Trade Quote",
  nav: [
    { label: "Story", href: "#story" },
    { label: "Quality", href: "#quality" },
    { label: "Products", href: "#products" },
    { label: "Impact", href: "#impact" },
    { label: "Export", href: "#export" },
    { label: "Contact", href: "#contact" },
  ],
};
